import allure
def test_definition_in_labels():
    allure.dynamic.manual()
    allure.dynamic.parent_suite("gossocnill-4804")
    allure.dynamic.severity("high")
    allure.dynamic.suite('number #8')
    allure.dynamic.sub_suite('#75')
    allure.dynamic.testcase("5308")
    allure.dynamic.title("Тестирование сценария с поиском ишью на гитхабе")
    allure.dynamic.tag("recipients")
    allure.dynamic.link("https://github.com")
    allure.dynamic.description("new history inherited the part of functions from its parent history")
    allure.dynamic.description_html("<h1>new history of recipients</h1>")
    allure.dynamic.epic("starmain")
    allure.dynamic.feature("one more starmain")
    allure.dynamic.id("recipient_id = 2868" )
    allure.dynamic.issue("#648")
    allure.dynamic.label("owner", "obondareva")
